server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # 静态资源长缓存
  location /_next/static/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  # trailingSlash: true → 优先匹配目录形式
  location / {
    try_files $uri $uri/ $uri.html /index.html;
  }

  gzip on;
  gzip_types text/plain text/css application/javascript application/json image/svg+xml;
}
