export type Locale = 'zh' | 'en';

export const dict = {
  zh: {
    nav: {
      product: '产品',
      solutions: '解决方案',
      pricing: '定价',
      about: '关于',
      cta: '申请试用',
    },
    hero: {
      eyebrow: '企业级 AI 运行时基础设施',
      h1Line1: '一个 API，接入全球主流模型',
      h1Line2: '内置多通道容灾与智能路由',
      sub: 'Thynoria 为出海团队提供统一的 AI 接入与运行时层，聚合 OpenAI、Anthropic、Google、DeepSeek 等模型供应商，提供毫秒级故障切换、企业级治理与香港主体合规。',
      cta1: '申请试用',
      cta2: '联系我们',
      tag1: '香港主体',
      tag2: '合规可控',
      tag3: '多语言支持',
      tag4: '明确 SLA',
      codeLabel: 'Python · 接入示例',
      codeComment: '# 主通道异常时毫秒级自动切换，流式响应不中断',
    },
    pain: {
      eyebrow: '常见挑战',
      heading: '出海团队在生产环境的典型问题',
      sub: '基于与多家早期客户的访谈整理。',
      items: [
        {
          title: '上游故障期间业务连续性中断',
          desc: '主流模型供应商发生区域性故障时，未做多通道准备的应用通常需要数十分钟至数小时才能恢复服务。',
        },
        {
          title: '中转服务无法满足企业合规要求',
          desc: '出海公司主体大多在香港、新加坡或美国，需要正规合同与中英双语发票。多数中转服务无法提供这些合规材料。',
        },
        {
          title: '多供应商混用造成管理碎片化',
          desc: '不同供应商的协议、计费方式与配额限制各不相同。当账户增多后，账单核算、额度调度与故障定位都难以维护。',
        },
      ],
    },
    architecture: {
      eyebrow: '解决方案',
      heading: 'Thynoria 接入层',
      sub: '位于应用与模型供应商之间的中间层，提供统一接入、智能路由、可靠性保障与企业级治理能力。',
      apps: '应用层',
      appsList: 'Web · Mobile · Agent · 后端服务',
      layer: 'Thynoria 接入层',
      layerItems: ['负载均衡', '安全过滤', '智能路由', '故障切换'],
      providers: '模型供应商',
      providersList: 'OpenAI · Anthropic · Google · Azure · DeepSeek',
    },
    stack: {
      eyebrow: '产品',
      heading: '四层基础设施能力',
      sub: '从接入到治理，覆盖企业 AI 应用在生产环境中的关键运行需求。',
      items: [
        {
          tag: '01',
          title: '统一接入',
          subtitle: 'AI 网关',
          desc: '兼容 OpenAI 协议的统一接入层，背后聚合 OpenAI、Anthropic、Google Gemini、DeepSeek 等主流模型。一套凭据完成多模型接入，业务代码无需改造。',
        },
        {
          tag: '02',
          title: '智能路由',
          subtitle: '多模型编排',
          desc: '基于延迟、成本与模型能力的动态路由。支持按业务场景选择最优通道，并可配置主备策略与权重。',
        },
        {
          tag: '03',
          title: '可靠性层',
          subtitle: '稳定性保障',
          desc: '毫秒级故障切换、熔断降级、流式响应接续。通过多通道智能容灾，保障生产环境中的业务连续性。',
        },
        {
          tag: '04',
          title: '安全治理',
          subtitle: '合规与治理',
          desc: '提供企业级审计日志、Token 配额管理、内容安全过滤与权限治理。香港主体运营，提供明确的 SLA 承诺。',
        },
      ],
    },
    compare: {
      eyebrow: '对比',
      heading: '与其他方案的差异',
      sub: '从目标客户、合规性与可靠性能力等维度，对比 Thynoria 与常见的 AI 接入方案。',
      cols: ['维度', 'OpenRouter', '国内中转服务', '官方直连', 'Thynoria'],
      rows: [
        ['目标客户', '全球开发者', '大陆个人开发者', '全球企业', '亚太地区出海团队'],
        ['定价策略', '略有折扣', '低于官方价', '官方价', '官方价'],
        ['多通道容灾', '有限支持', '不支持', '不支持', '毫秒级自动切换'],
        ['合同发票', '不提供中文', '不透明', '美元 · 英文', '港币 · 中英双语'],
        ['客户支持', '英文 · Discord', '微信群', '工单系统', '中文 · 专属对接'],
        ['SLA 承诺', '无', '无', '无明确承诺', '明确 SLA 与违约责任'],
        ['主体合规', '海外', '不透明', '海外', '香港注册公司'],
      ],
    },
    fit: {
      eyebrow: '适用范围',
      heading: '我们适合什么样的客户',
      sub: '基于产品设计目标的客观说明。',
      fitLabel: '适合',
      notFitLabel: '不适合',
      fit: [
        '公司主体注册在香港、新加坡或美国的出海团队',
        '生产环境应用，对稳定性的优先级高于成本优化',
        '需要正规合同发票与多语言技术支持的企业客户',
        '同时使用多家模型供应商，需要统一接入与治理',
      ],
      notFit: [
        '主体与业务均在中国大陆境内的公司',
        '主要诉求是显著低于官方价格的成本优化',
        '个人开发者及非生产环境的实验项目',
      ],
    },
    seed: {
      tag: '限 3 个名额',
      eyebrow: '定价',
      heading: '早期合作伙伴计划',
      sub: '产品处于早期阶段，向前 3 家种子客户开放合作席位。',
      perks: [
        '首 6 个月费用 50% 折扣',
        '创始人直接对接，故障可即时响应',
        '产品需求优先纳入路线图',
        '永久锁定种子客户价格',
      ],
      exchange: '作为合作交换，希望客户每两周提供约 30 分钟的产品反馈。',
      cta1: '申请合作',
      cta2: '联系我们',
    },
    founder: {
      eyebrow: '关于',
      heading: '关于创始人',
      lines: [
        'Larry Chen，Thynoria 创始人。',
        '创办 Thynoria 之前，曾在生产环境多次经历主流模型供应商的区域性故障，并在多个项目中自行实现跨供应商的容灾与故障切换机制。',
        'AI 基础设施的核心价值，在于异常情况下维持业务的连续性。',
        'Thynoria 基于上述经验构建，目标用户是面临相同问题的出海团队。',
      ],
      contactLabel: '联系邮箱：',
    },
    contact: {
      eyebrow: '联系',
      heading: '申请合作',
      sub: '我们会在 24 小时内回复，并约一次 30 分钟的视频沟通。',
      okMessage: '已收到，我们会尽快通过邮件与你联系。',
      okSub: '如有紧急事项可直接发送邮件至 larrchen0125@gmail.com',
      labels: {
        email: '邮箱',
        entity: '公司主体注册地',
        spend: '月度 AI API 花费量级',
        scenario: '业务场景及主要问题（选填）',
      },
      placeholders: {
        email: 'you@company.com',
        select: '请选择',
        scenario: '简要描述使用场景与目前面临的主要问题。',
      },
      entityOptions: [
        ['HK', '香港'],
        ['SG', '新加坡'],
        ['US', '美国'],
        ['CN', '中国大陆'],
        ['OTHER', '其他'],
      ] as [string, string][],
      spendOptions: [
        ['<1k', '< $1,000'],
        ['1k-10k', '$1,000 – $10,000'],
        ['10k-100k', '$10,000 – $100,000'],
        ['>100k', '> $100,000'],
      ] as [string, string][],
      submit: '提交申请',
      submitting: '提交中…',
      errPrefix: '提交失败：',
      errSuffix: '，可尝试发送邮件至 larrchen0125@gmail.com',
      privacy: '提交的信息仅用于业务对接，不会与任何第三方共享。',
    },
    footer: {
      slogan: '企业级 AI 运行时基础设施',
      contactTitle: '联系',
      companyTitle: '公司',
      companyL1: 'Thynoria Limited',
      companyL2: '注册于中国香港',
      legal: 'Thynoria 是注册于中国香港的服务提供商，面向全球开发者提供 AI API 聚合服务，不主动向中国大陆境内提供服务。所有用户对自身的合规使用承担全部责任。',
      rights: '保留所有权利。',
    },
  },

  en: {
    nav: {
      product: 'Product',
      solutions: 'Solutions',
      pricing: 'Pricing',
      about: 'About',
      cta: 'Request Access',
    },
    hero: {
      eyebrow: 'Enterprise AI Runtime Infrastructure',
      h1Line1: 'One API for every major model.',
      h1Line2: 'Built-in failover and smart routing.',
      sub: 'Thynoria is a unified AI access and runtime layer for teams operating across borders. We aggregate providers including OpenAI, Anthropic, Google, and DeepSeek, with millisecond failover, enterprise-grade governance, and a Hong Kong-registered entity.',
      cta1: 'Request Access',
      cta2: 'Contact Us',
      tag1: 'Hong Kong Entity',
      tag2: 'Compliant',
      tag3: 'Multilingual Support',
      tag4: 'Documented SLA',
      codeLabel: 'Python · Example',
      codeComment: '# Primary fails → millisecond auto-fallback, streaming preserved',
    },
    pain: {
      eyebrow: 'Common Challenges',
      heading: 'Typical problems in production',
      sub: 'Drawn from interviews with early customers.',
      items: [
        {
          title: 'Business continuity drops during upstream outages',
          desc: 'When a major model provider experiences a regional outage, applications without multi-channel preparation typically take tens of minutes to several hours to recover.',
        },
        {
          title: 'Relay services fall short on enterprise compliance',
          desc: 'Teams operating across borders are typically registered in Hong Kong, Singapore, or the United States and require formal contracts and bilingual invoices, which most relay services cannot provide.',
        },
        {
          title: 'Multi-provider sprawl fragments management',
          desc: 'Providers differ in protocols, billing models, and quota policies. As accounts accumulate, reconciliation, capacity planning, and incident triage become hard to maintain.',
        },
      ],
    },
    architecture: {
      eyebrow: 'Solutions',
      heading: 'The Thynoria Layer',
      sub: 'A layer between your application and the world\'s models — providing unified access, smart routing, reliability guarantees and enterprise governance.',
      apps: 'Application Layer',
      appsList: 'Web · Mobile · Agent · Backends',
      layer: 'Thynoria Layer',
      layerItems: ['Load Balancer', 'Security Filter', 'Smart Router', 'Fallback Logic'],
      providers: 'Model Providers',
      providersList: 'OpenAI · Anthropic · Google · Azure · DeepSeek',
    },
    stack: {
      eyebrow: 'Product',
      heading: 'Four infrastructure layers',
      sub: 'From access to governance, covering the operational concerns of AI in production.',
      items: [
        {
          tag: '01',
          title: 'Connectivity',
          subtitle: 'AI Gateway',
          desc: 'An OpenAI-compatible unified ingress aggregating OpenAI, Anthropic, Google Gemini, DeepSeek and other major models. One credential, no code changes.',
        },
        {
          tag: '02',
          title: 'Intelligence',
          subtitle: 'Multi-Model Orchestration',
          desc: 'Dynamic routing based on latency, cost, and model capability. Choose the optimal channel per workload, with configurable primary/backup strategies and weights.',
        },
        {
          tag: '03',
          title: 'Resilience',
          subtitle: 'Reliability Layer',
          desc: 'Millisecond failover, circuit breakers, and continuity for streaming responses. Multi-channel resilience preserves business continuity in production.',
        },
        {
          tag: '04',
          title: 'Trust',
          subtitle: 'Governance & Compliance',
          desc: 'Enterprise-grade audit logs, token-budget management, content safety filtering, and RBAC. Operated from a Hong Kong entity with a documented SLA.',
        },
      ],
    },
    compare: {
      eyebrow: 'Comparison',
      heading: 'How we compare',
      sub: 'Differences across target customers, compliance, and reliability capabilities.',
      cols: ['Dimension', 'OpenRouter', 'CN Relays', 'Direct API', 'Thynoria'],
      rows: [
        ['Target Customer', 'Global developers', 'Individual CN developers', 'Global enterprise', 'APAC teams going global'],
        ['Pricing', 'Slight discount', 'Below list price', 'List price', 'List price'],
        ['Failover', 'Limited', 'None', 'None', 'Millisecond auto-switch'],
        ['Invoicing', 'No Chinese', 'Opaque', 'USD · English', 'HKD · Bilingual'],
        ['Support', 'English · Discord', 'WeChat group', 'Ticket system', 'Chinese · dedicated'],
        ['SLA', 'None', 'None', 'No commitment', 'Documented SLA & remedy'],
        ['Entity', 'Offshore', 'Opaque', 'Offshore', 'Hong Kong registered'],
      ],
    },
    fit: {
      eyebrow: 'Right Fit',
      heading: 'Who we serve',
      sub: 'A neutral statement of the customers we designed for.',
      fitLabel: 'Good fit',
      notFitLabel: 'Not a fit',
      fit: [
        'Teams operating across borders with entities in Hong Kong, Singapore, or the United States',
        'Production workloads where reliability outranks cost optimization',
        'Enterprise customers requiring formal invoicing and multilingual support',
        'Teams using multiple model providers and seeking unified governance',
      ],
      notFit: [
        'Companies whose entity and operations are both in mainland China',
        'Primary requirement is significantly below-market pricing',
        'Individual developers and non-production experimental projects',
      ],
    },
    seed: {
      tag: 'Limited to 3 partners',
      eyebrow: 'Pricing',
      heading: 'Early access partner program',
      sub: 'During early access, we offer partnership slots to three seed customers.',
      perks: [
        '50% discount for the first six months',
        'Direct line to the founder for incident response',
        'Product requirements prioritized into the roadmap',
        'Permanently locked seed-partner pricing',
      ],
      exchange: 'In exchange, partners provide roughly 30 minutes of product feedback every two weeks.',
      cta1: 'Apply for partnership',
      cta2: 'Contact us',
    },
    founder: {
      eyebrow: 'About',
      heading: 'About the founder',
      lines: [
        'Larry Chen, founder of Thynoria.',
        'Before founding Thynoria, I went through multiple regional outages from major model providers in production environments and implemented cross-provider failover and recovery mechanisms across several projects.',
        'The core value of AI infrastructure lies in maintaining business continuity during anomalies.',
        'Thynoria is built on those experiences and targets teams operating across borders that face the same problems.',
      ],
      contactLabel: 'Contact email:',
    },
    contact: {
      eyebrow: 'Contact',
      heading: 'Apply for partnership',
      sub: 'We respond within 24 hours and schedule a 30-minute video call.',
      okMessage: 'Received. We will reach out by email shortly.',
      okSub: 'For anything urgent, email larrchen0125@gmail.com.',
      labels: {
        email: 'Email',
        entity: 'Company entity location',
        spend: 'Monthly AI API spend',
        scenario: 'Use case and main pain points (optional)',
      },
      placeholders: {
        email: 'you@company.com',
        select: 'Select…',
        scenario: 'Briefly describe your use case and current pain points.',
      },
      entityOptions: [
        ['HK', 'Hong Kong'],
        ['SG', 'Singapore'],
        ['US', 'United States'],
        ['CN', 'Mainland China'],
        ['OTHER', 'Other'],
      ] as [string, string][],
      spendOptions: [
        ['<1k', '< $1,000'],
        ['1k-10k', '$1,000 – $10,000'],
        ['10k-100k', '$10,000 – $100,000'],
        ['>100k', '> $100,000'],
      ] as [string, string][],
      submit: 'Submit',
      submitting: 'Submitting…',
      errPrefix: 'Submission failed: ',
      errSuffix: '. You can also email larrchen0125@gmail.com',
      privacy: 'Your information will only be used for business contact and will not be shared with third parties.',
    },
    footer: {
      slogan: 'Enterprise AI Runtime Infrastructure',
      contactTitle: 'Contact',
      companyTitle: 'Company',
      companyL1: 'Thynoria Limited',
      companyL2: 'Registered in Hong Kong',
      legal: 'Thynoria is a service provider registered in Hong Kong, offering AI API aggregation services globally. It does not actively target users in mainland China. Each user is fully responsible for their own compliance.',
      rights: 'All rights reserved.',
    },
  },
};

export type Dict = typeof dict.zh;
