export type Locale = 'zh' | 'en';

export const dict = {
  zh: {
    nav: {
      stack: 'Stack',
      architecture: '架构',
      compare: '对比',
      contact: '联系',
      cta: '申请内测',
    },
    hero: {
      eyebrow: 'RELIABILITY INFRASTRUCTURE FOR ENTERPRISE AI',
      h1Line1: '停止管理 API。',
      h1Line2: '开始构建 AI。',
      sub: '面向出海 AI 团队的企业级 AI Runtime Infrastructure。一套凭据，统一接入全球主流模型；毫秒级容灾，让生产环境真正具备生产能力。',
      cta1: '申请内测',
      cta2: '联系创始人',
      tag1: '香港主体',
      tag2: '合规透明',
      tag3: '中英双语',
      tag4: 'SLA 承诺',
      codeLabel: 'PYTHON · 业务代码零改造',
      codeComment: '# 主通道异常 → 毫秒级自动切换，流式响应不中断',
    },
    pain: {
      eyebrow: 'WHY THYNORIA',
      heading: '生产环境中的真实问题',
      sub: '这些场景，你大概都经历过。',
      items: [
        {
          title: 'OpenAI 抽风 18 分钟，业务就停了 18 分钟',
          desc: '没有 Plan B，没有自动切换，没有告警。等你发现，客户已经在用竞品。',
        },
        {
          title: '用中转站，月底报销发票拿不出来',
          desc: '公司主体在香港 / 新加坡，财务要的是正规合同与中英双语发票。中转站连真实主体都不愿告诉你。',
        },
        {
          title: '7 家供应商 12 个 key，账单没人说得清',
          desc: 'OpenAI、Azure、Claude、Gemini、DeepSeek——协议、计费、配额各不相同，出问题时日志都拼不出来。',
        },
      ],
    },
    architecture: {
      eyebrow: 'ARCHITECTURE',
      heading: 'Thynoria Layer',
      sub: '介于你的应用与全球模型之间的可靠性层。不是中转，是基础设施。',
      apps: '你的应用',
      appsList: 'Web · Mobile · Agent · 后端服务',
      layer: 'Thynoria Layer',
      layerItems: ['Load Balancer', 'Security Filter', 'Smart Router', 'Fallback Logic'],
      providers: '全球模型供应商',
      providersList: 'OpenAI · Anthropic · Google · Azure · DeepSeek',
    },
    stack: {
      eyebrow: 'THYNORIA STACK',
      heading: '不只是网关，是一整套企业级运行时',
      sub: '从接入到治理，四层基础设施，覆盖企业 AI 生产环境的全部关键能力。',
      items: [
        {
          tag: '01',
          title: 'Connectivity',
          subtitle: 'AI Gateway',
          desc: '兼容 OpenAI 协议的统一接入层，背后聚合 OpenAI、Anthropic、Gemini、DeepSeek 等全球主流模型。一套凭据，零代码改造。',
        },
        {
          tag: '02',
          title: 'Intelligence',
          subtitle: 'Smart Routing',
          desc: '基于延迟、成本、模型能力的动态路由。按场景选择最优通道，不再为人肉切换烦恼。',
        },
        {
          tag: '03',
          title: 'Resilience',
          subtitle: 'Reliability Layer',
          desc: '毫秒级故障切换、熔断降级、流式响应接续。多通道智能容灾，把"出事时还活着"做成默认能力。',
        },
        {
          tag: '04',
          title: 'Trust',
          subtitle: 'Governance',
          desc: '企业级审计日志、Token 配额、内容安全、权限治理。香港主体、SLA 承诺、合规可控。',
        },
      ],
    },
    compare: {
      eyebrow: 'DIFFERENTIATION',
      heading: '为什么是 Thynoria',
      sub: '不与中转站打价格战，不与 OpenRouter 抢全球开发者市场。',
      cols: ['维度', 'OpenRouter', '国内中转站', '官方直连', 'Thynoria'],
      rows: [
        ['主战场', '全球开发者', '大陆个人开发者', '全球企业', '亚太华人出海企业'],
        ['定价策略', '略有折扣', '极低价', '标准', '标准价 · 不打价格战'],
        ['多通道容灾', '有限', '无', '无', '毫秒级自动切换'],
        ['合同发票', '无中文', '模糊', '美元英文', '港币 · 中英双语'],
        ['客户支持', '英文 · Discord', '微信群', '工单', '中文 · 1v1 专属群'],
        ['SLA 承诺', '无', '无', '无明确', '明确 SLA 与违约责任'],
        ['主体合规', '海外', '不透明', '海外', '香港正规公司'],
      ],
    },
    fit: {
      eyebrow: 'HONEST BOUNDARIES',
      heading: '我们不适合所有人',
      sub: '坦诚的边界，胜过空洞的承诺。',
      fitLabel: '适合',
      notFitLabel: '不适合',
      fit: [
        '公司主体在 香港 / 新加坡 / 美国 的出海 AI 团队',
        '业务跑在生产环境，稳定性比省 5% 成本更重要',
        '需要合规发票、需要中文支持的港新美主体公司',
        '一线在踩 API 故障与多供应商管理的坑',
      ],
      notFit: [
        '公司主体与业务都在中国大陆境内',
        '主要诉求是"比官方便宜 30%"',
        '个人开发者 / Hobby 项目',
      ],
    },
    seed: {
      tag: '仅 3 个名额',
      eyebrow: 'EARLY ACCESS',
      heading: '招募前 3 家种子客户',
      sub: '内测阶段，我们正在邀请 3 家种子客户共建产品。',
      perks: [
        '前 6 个月费用半价',
        '创始人微信 1v1 兜底，故障半夜也回',
        '优先功能开发权，需求进入首版路线图',
        '永久锁定种子客户价，未来不调价',
      ],
      exchange: '作为交换，我们希望你愿意每两周给我们 30 分钟反馈。',
      cta1: '申请加入种子客户',
      cta2: '先聊聊',
    },
    founder: {
      eyebrow: 'FOUNDER NOTE',
      heading: '关于创始人',
      lines: [
        '我是 Larry Chen，Thynoria 的创始人。',
        '在创办 Thynoria 之前，我曾在生产环境亲历过多次 OpenAI、Anthropic 的区域性故障，也亲手用胶带和铁丝把多通道容灾这件事缝合过无数次。',
        'AI 基础设施的价值，不在于平时跑得多快，而在于出事时还活着。',
        'Thynoria 是我把这些年踩过的坑沉淀下来，做给和我有同样烦恼的出海 AI 团队的工具。',
      ],
      contactLabel: '如果你也在踩同样的坑，欢迎随时找我聊：',
    },
    contact: {
      eyebrow: 'GET IN TOUCH',
      heading: '申请加入种子客户',
      sub: '我们会在 24 小时内回复，并约一次 30 分钟的视频沟通。',
      okMessage: '已收到，我们会尽快通过邮件与你联系。',
      okSub: '如有紧急事项可直接发邮件至 larrchen0125@gmail.com',
      labels: {
        email: '邮箱',
        entity: '公司主体注册地',
        spend: '月度 AI API 花费量级',
        scenario: '一句话描述你的业务场景与最痛的点（选填）',
      },
      placeholders: {
        email: 'you@company.com',
        select: '请选择',
        scenario: '例如：跨境电商 AI 客服，每次 OpenAI 抽风都丢单……',
      },
      entityOptions: [
        ['HK', '香港'],
        ['SG', '新加坡'],
        ['US', '美国'],
        ['CN', '中国大陆'],
        ['OTHER', '其他'],
      ] as [string, string][],
      spendOptions: [
        ['<1k', '< $1,000'],
        ['1k-10k', '$1,000 – $10,000'],
        ['10k-100k', '$10,000 – $100,000'],
        ['>100k', '> $100,000'],
      ] as [string, string][],
      submit: '提交申请',
      submitting: '提交中…',
      errPrefix: '提交失败：',
      errSuffix: '。也可直接发邮件至 larrchen0125@gmail.com',
      privacy: '我们承诺不向任何第三方分享你的信息。',
    },
    footer: {
      slogan: 'Reliability Infrastructure for Enterprise AI',
      contactTitle: '联系',
      companyTitle: '公司',
      companyL1: 'Thynoria Limited',
      companyL2: 'Registered in Hong Kong',
      legal: 'Thynoria 是注册于香港的服务提供商，面向全球开发者提供 AI API 聚合服务，不主动向中国大陆境内提供服务。所有用户对自身的合规使用承担全部责任。',
      rights: 'All rights reserved.',
    },
  },
  en: {
    nav: {
      stack: 'Stack',
      architecture: 'Architecture',
      compare: 'Compare',
      contact: 'Contact',
      cta: 'Request Access',
    },
    hero: {
      eyebrow: 'RELIABILITY INFRASTRUCTURE FOR ENTERPRISE AI',
      h1Line1: 'Stop managing APIs.',
      h1Line2: 'Start building AI.',
      sub: 'Enterprise-grade AI Runtime Infrastructure for teams going global. One credential to access every major model — with millisecond failover that keeps production alive.',
      cta1: 'Request Access',
      cta2: 'Talk to Founder',
      tag1: 'Hong Kong Entity',
      tag2: 'Compliant',
      tag3: 'Bilingual Support',
      tag4: 'SLA-backed',
      codeLabel: 'PYTHON · DROP-IN REPLACEMENT',
      codeComment: '# Primary fails → millisecond fallback, streaming preserved',
    },
    pain: {
      eyebrow: 'WHY THYNORIA',
      heading: 'Real problems in production',
      sub: 'You\'ve probably hit all of these.',
      items: [
        {
          title: 'OpenAI hiccups for 18 min — your app is down 18 min',
          desc: 'No Plan B, no auto-failover, no alerts. By the time you notice, your customer is on a competitor.',
        },
        {
          title: 'Can\'t expense the monthly bill from a relay site',
          desc: 'Your HK / SG entity needs proper contracts and bilingual invoices. Relays won\'t even disclose their corporate entity.',
        },
        {
          title: '7 providers, 12 keys, nobody knows the bill',
          desc: 'Every vendor has a different protocol, pricing, and quota. When something breaks, you can\'t even stitch the logs together.',
        },
      ],
    },
    architecture: {
      eyebrow: 'ARCHITECTURE',
      heading: 'The Thynoria Layer',
      sub: 'A reliability layer between your application and the world\'s models. Not a relay — infrastructure.',
      apps: 'Your Apps',
      appsList: 'Web · Mobile · Agent · Backends',
      layer: 'Thynoria Layer',
      layerItems: ['Load Balancer', 'Security Filter', 'Smart Router', 'Fallback Logic'],
      providers: 'Global Model Providers',
      providersList: 'OpenAI · Anthropic · Google · Azure · DeepSeek',
    },
    stack: {
      eyebrow: 'THYNORIA STACK',
      heading: 'More than a gateway — a full runtime',
      sub: 'Four infrastructure layers covering every critical concern in production AI.',
      items: [
        {
          tag: '01',
          title: 'Connectivity',
          subtitle: 'AI Gateway',
          desc: 'OpenAI-compatible unified ingress for OpenAI, Anthropic, Gemini, DeepSeek and more. One credential, no code changes.',
        },
        {
          tag: '02',
          title: 'Intelligence',
          subtitle: 'Smart Routing',
          desc: 'Dynamic routing based on latency, cost and model capability. Best channel per workload, automatically.',
        },
        {
          tag: '03',
          title: 'Resilience',
          subtitle: 'Reliability Layer',
          desc: 'Millisecond failover, circuit breakers, streaming continuity. Multi-channel resilience as a default capability.',
        },
        {
          tag: '04',
          title: 'Trust',
          subtitle: 'Governance',
          desc: 'Audit logs, token budgets, content safety, RBAC. Hong Kong entity, SLA-backed, compliant by design.',
        },
      ],
    },
    compare: {
      eyebrow: 'DIFFERENTIATION',
      heading: 'Why Thynoria',
      sub: 'We don\'t compete on price with relays, nor on scale with OpenRouter.',
      cols: ['Dimension', 'OpenRouter', 'CN Relays', 'Direct API', 'Thynoria'],
      rows: [
        ['Audience', 'Global devs', 'CN individuals', 'Global enterprise', 'APAC teams going global'],
        ['Pricing', 'Slight discount', 'Rock-bottom', 'Standard', 'Standard · no price wars'],
        ['Failover', 'Limited', 'None', 'None', 'Millisecond auto-switch'],
        ['Invoicing', 'No Chinese', 'Vague', 'USD English', 'HKD · Bilingual'],
        ['Support', 'English · Discord', 'WeChat group', 'Ticket', '1:1 Chinese channel'],
        ['SLA', 'None', 'None', 'No commitment', 'Documented SLA & remedy'],
        ['Entity', 'Offshore', 'Opaque', 'Offshore', 'Hong Kong registered'],
      ],
    },
    fit: {
      eyebrow: 'HONEST BOUNDARIES',
      heading: 'We aren\'t for everyone',
      sub: 'An honest boundary beats an empty promise.',
      fitLabel: 'Right fit',
      notFitLabel: 'Not a fit',
      fit: [
        'Entities in HK / Singapore / US going global',
        'Production workloads where uptime beats 5% cost saving',
        'Teams needing compliant invoicing & Chinese-language support',
        'Engineers actively wrestling with multi-provider chaos',
      ],
      notFit: [
        'Both entity & business based in mainland China',
        'Primary need is "30% cheaper than the official API"',
        'Solo / hobby projects',
      ],
    },
    seed: {
      tag: 'Only 3 spots',
      eyebrow: 'EARLY ACCESS',
      heading: 'Seeking 3 design-partner customers',
      sub: 'We\'re in early access, inviting 3 customers to co-build the product.',
      perks: [
        '50% off for the first 6 months',
        'Founder on speed-dial — including 2 AM outages',
        'Priority roadmap — your needs go first',
        'Locked-in pricing forever — no future hikes',
      ],
      exchange: 'In exchange, we ask for 30 minutes of feedback every two weeks.',
      cta1: 'Apply as design partner',
      cta2: 'Just say hi',
    },
    founder: {
      eyebrow: 'FOUNDER NOTE',
      heading: 'About the founder',
      lines: [
        'I\'m Larry Chen, founder of Thynoria.',
        'Before starting Thynoria, I\'d been through every flavor of OpenAI / Anthropic regional outage in production, and stitched multi-channel failover together with duct tape more times than I\'d like to admit.',
        'The value of AI infrastructure isn\'t how fast it runs day to day — it\'s whether it survives when things break.',
        'Thynoria is what I wish existed back then, built for teams hitting the same walls.',
      ],
      contactLabel: 'If any of this resonates, find me at:',
    },
    contact: {
      eyebrow: 'GET IN TOUCH',
      heading: 'Apply as a design partner',
      sub: 'We reply within 24 hours and schedule a 30-minute video call.',
      okMessage: 'Received. We\'ll reach out by email shortly.',
      okSub: 'For anything urgent, email larrchen0125@gmail.com',
      labels: {
        email: 'Email',
        entity: 'Company entity location',
        spend: 'Monthly AI API spend',
        scenario: 'Briefly describe your use case & biggest pain (optional)',
      },
      placeholders: {
        email: 'you@company.com',
        select: 'Select…',
        scenario: 'e.g. cross-border AI customer support, losing orders every time OpenAI hiccups…',
      },
      entityOptions: [
        ['HK', 'Hong Kong'],
        ['SG', 'Singapore'],
        ['US', 'United States'],
        ['CN', 'Mainland China'],
        ['OTHER', 'Other'],
      ] as [string, string][],
      spendOptions: [
        ['<1k', '< $1,000'],
        ['1k-10k', '$1,000 – $10,000'],
        ['10k-100k', '$10,000 – $100,000'],
        ['>100k', '> $100,000'],
      ] as [string, string][],
      submit: 'Submit',
      submitting: 'Submitting…',
      errPrefix: 'Submission failed: ',
      errSuffix: '. You can also email larrchen0125@gmail.com',
      privacy: 'We will never share your information with third parties.',
    },
    footer: {
      slogan: 'Reliability Infrastructure for Enterprise AI',
      contactTitle: 'Contact',
      companyTitle: 'Company',
      companyL1: 'Thynoria Limited',
      companyL2: 'Registered in Hong Kong',
      legal: 'Thynoria is a service provider registered in Hong Kong, offering AI API aggregation services globally. We do not actively target users in mainland China. Each user is fully responsible for their own compliance.',
      rights: 'All rights reserved.',
    },
  },
};

export type Dict = typeof dict.zh;
